# Generated by Django 5.2.13 on 2026-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
