# Generated by Django 5.2.13 on 2026-05-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_in_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField()),
                ('order', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
