# Generated by Django 5.2.13 on 2026-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
